### ISSUE TITLE
Build to ESM

### ISSUE THREAD

**Issue by BlakeB415** [unitedwardrobe/imgproxy-node#13]
We use native ESM in our backend project. Other libraries are starting to become ESM-only so we were forced to switch. 

It would be nice to at least have this support ESM natively as well. Probably best to do dual ESM and CJS builds for compatibility.

**Comment by remq** [comment]
I'll put it on my backlog but it'll probably have a low priority unfortunately. Feel free to open a PR if you want it faster.
