### ISSUE TITLE
Ignore undefined arguments passed to resize()

### ISSUE THREAD

**Issue by ajsharp** [unitedwardrobe/imgproxy-node#3]
imgproxy supports ignoring certain arguments, such as height, when calling resize. If you call resize with only the width, it will automatically respect the source image dimensions. In this line https://github.com/unitedwardrobe/imgproxy-node/blob/b34198fd925a8572519baa67efea78108e3a10d6/src/builder.ts#L53 this library stringifies any value passed to it, so, if you pass `null` or `undefined`, the string "undefined" will be passed on to imgproxy. Ideally, this library would check for a truthy value before stringifying the value and ignoring falsey values.

**Comment by koenpunt** [comment]
I assume you mean this method?

https://github.com/unitedwardrobe/imgproxy-node/blob/b34198fd925a8572519baa67efea78108e3a10d6/src/builder.ts#L37-L40
