### ISSUE TITLE
Invalid URL to the Original Image

### ISSUE THREAD

**Issue by dario1985** [unitedwardrobe/imgproxy-node#7]
Trying to generate an URL to the original image (with no-transformations) generates an invalid URL:

```
imgproxy
  .builder()
  .generateUrl('https://example.com/path/to/image.jpg');
``` 

tested with imgproxy server version 2.4

NOTE: after adding some / (slashes) in the middle of the Base64 fix the problem.

**Comment by remq** [comment]
Closing it due to lack of response.
